# xdp_loader.conf - eBPF 控制面配置文件

# XDP 挂载网卡
# 本地虚拟机测试建议使用 lo
# 真机或真实网卡测试时可改为 ens33 / eth0
ifname=lo

# XDP 模式
# lo 或虚拟网卡建议 skb
# 真实网卡支持驱动模式时可改为 drv
xdp_mode=skb

# Unix Domain Socket 路径
# loader 作为服务端，Flask 后端作为客户端连接该路径
socket_path=/tmp/xdp_loader.sock

# 日志文件路径
log_file=/tmp/xdp_loader.log

# 统计输出周期，单位：秒
stats_interval_sec=5

# 是否后台运行
# 0 = 前台运行
# 1 = 后台守护进程运行
daemon=0
